# -*- coding: utf-8 -*-
"""Analise_Exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3qFdC_vXvcvxn1YOWBTOUCgwDEYIN30
"""

import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

#upload de arquivo
from google.colab import files
arq = files.upload()

df = pd.read_excel("AdventureWorks.xlsx")

df.head()

#quantidade de linhas e colunas
df.shape

df.dtypes

#qual a receita total
df["Valor Venda"].sum()

df["Custo total"] = df["Custo Unitário"].mul(df["Quantidade"])
df["Custo total"]

df.head()

#custo total arredondado para 2 casas decimais 
round(df['Custo total'].sum(), 2)

#vamos achar o lucro real - criando uma nova coluna de lucro

df["Lucro"] = df['Valor Venda'] - df["Custo total"]

df.head(1)

#total Lucro
round(df['Lucro'].sum(), 2)

#criando uma coluna para dizer o total dias que demorou para envias os produtos

df["Tempo envio"] =df["Data Envio"] - df["Data Venda"]

df.head(1)

#extraindo apenas os dias
df["Tempo envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

df["Tempo envio"].dtypes

#Média de tempo de envio por marca
round(df.groupby("Marca")["Tempo envio"].mean(), 2)

#verificando se tem valores ausentes
df.isnull().sum()

#Agrupar por ano e por marca
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

pd.options.display.float_format = '{:,.2f}'.format

#Resetando o index
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()
lucro_ano

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False).reset_index()

df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro x Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum()

#Selecionando apenas a s vendas de 2009
df_2009 = df.loc[(df["Data Venda"].dt.year==2009)]
df_2009.head()

df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro x Mês")
plt.xlabel("Mês")
plt.ylabel("Lucros")

df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="Lucro x Marca")
plt.xlabel("Marca")
plt.ylabel("Lucros")
plt.xticks(rotation="horizontal");

df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title="Lucro x Classe")
plt.xlabel("Classe")
plt.ylabel("Lucros")
plt.xticks(rotation="horizontal"); #a legenda debaixo fica na horizontal

df["Tempo envio"].describe()

#Gráfico de BoxPlot
plt.boxplot(df["Tempo envio"]);

#Histograma
plt.hist(df["Tempo envio"]);

df.to_csv("df_vendas_novo.csv", index=False)

